server:
  address: localhost
  port: 9616
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/nailshop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: sdfgsd7sdg78sdgsdsddsdssdgds564gf65se4v1vt531918hfgg9h81lk489p45yt4e64e1gg06fd01s231gs3016g54wey7we9g79ds6464sdg4sd9ds8g798w7g9gq9ge9g98cvbcv6n44sgh3sd4g3hds3